name: Node CI
on:
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-node@v1
       with:
        node-version: 12.x
     - name: Npm Install
       run: npm install 
     - name: Run Script
       run: node main.js
       env:
        gist_id: ${{secrets.gist_id}}
        gist_token: ${{secrets.gist_token}}
