name: Node CI
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Npm install
      run: |
          npm install 
    - name: Run Script
      run: |
          node main.js
      env:
        gist_id: ${{secrets.gist_id}}
        gist_token: ${{secrets.gist_token}}
